# -*- mode: ruby -*-
# vi: set ft=ruby :

# Définition des variables
RAM = 1024
CPU = 1
IP_LB = "10.0.0.10"
IP_WEB1 = "10.0.0.11"
IP_WEB2 = "10.0.0.12"
BOX = "ubuntu/trusty64"

Vagrant.configure("2") do |config|
  
  # Configure load balancer machine
  config.vm.define "lb" do |lb|
    lb.vm.box = BOX
    lb.vm.network "private_network", ip: IP_LB
  end

  # configure first web machine
  config.vm.define "web1" do |web1|
    web1.vm.box = BOX
    web1.vm.network "private_network", ip: IP_WEB1
  end

  # configure second web machine
  config.vm.define "web2" do |web2|
    web2.vm.box = BOX
    web2.vm.network "private_network", ip: IP_WEB2
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = RAM
    v.cpus = CPU
  end
  
end
